/* eslint-disable */
// This file is generated by esbuild. Do not edit it directly.

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MdToHtmlItalicsCheckerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var INLINE_CODE_PATTERN = /(`[^`]*`)/g;
var BOLD_PATTERN = /(^|[^\\*])\*\*([^*\n]+?)\*\*(?=($|[^\\*]))/g;
var ASTERISK_ITALIC_PATTERN = /(^|[^\\*])\*([^*\n]+?)\*(?=($|[^\\*]))/g;
var UNDERSCORE_ITALIC_PATTERN = /(^|[^\\\w])_([^_\n]+?)_(?=($|[^\w]))/g;
var BADGE_CLASS = "md-to-html-issue-badge";
var REPORT_VIEW_TYPE = "md-to-html-report-view";
function convertSegment(segment) {
  let count = 0;
  const boldConverted = segment.replace(
    BOLD_PATTERN,
    (fullMatch, prefix, content) => {
      count += 1;
      return `${prefix}<b>${content}</b>`;
    }
  );
  const asteriskItalicConverted = boldConverted.replace(
    ASTERISK_ITALIC_PATTERN,
    (fullMatch, prefix, content) => {
      count += 1;
      return `${prefix}<i>${content}</i>`;
    }
  );
  const value = asteriskItalicConverted.replace(
    UNDERSCORE_ITALIC_PATTERN,
    (fullMatch, prefix, content) => {
      count += 1;
      return `${prefix}<i>${content}</i>`;
    }
  );
  return { count, value };
}
function convertMarkdownFormatting(text) {
  const lines = text.split("\n");
  let insideFence = false;
  let totalCount = 0;
  const convertedLines = lines.map((line) => {
    if (/^\s*```/.test(line)) {
      insideFence = !insideFence;
      return line;
    }
    if (insideFence) {
      return line;
    }
    const parts = line.split(INLINE_CODE_PATTERN);
    const convertedParts = parts.map((part) => {
      if (part.startsWith("`") && part.endsWith("`")) {
        return part;
      }
      const result = convertSegment(part);
      totalCount += result.count;
      return result.value;
    });
    return convertedParts.join("");
  });
  return {
    count: totalCount,
    value: convertedLines.join("\n")
  };
}
function findFirstMatchLocation(text) {
  const lines = text.split("\n");
  let insideFence = false;
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex += 1) {
    const line = lines[lineIndex];
    if (/^\s*```/.test(line)) {
      insideFence = !insideFence;
      continue;
    }
    if (insideFence) {
      continue;
    }
    let cursor = 0;
    const parts = line.split(INLINE_CODE_PATTERN);
    for (const part of parts) {
      const partStart = cursor;
      cursor += part.length;
      if (part.startsWith("`") && part.endsWith("`")) {
        continue;
      }
      const matches = [BOLD_PATTERN, ASTERISK_ITALIC_PATTERN, UNDERSCORE_ITALIC_PATTERN].map((matcher) => {
        matcher.lastIndex = 0;
        const match = matcher.exec(part);
        if (!match || match.index === void 0) {
          return null;
        }
        return { matcher, match };
      }).filter((entry) => entry !== null).sort((left, right) => left.match.index - right.match.index);
      const firstMatch = matches[0];
      if (firstMatch) {
        const prefix = firstMatch.match[1] ?? "";
        const content = firstMatch.match[2] ?? "";
        const startCh = partStart + firstMatch.match.index + prefix.length;
        const endCh = startCh + content.length + (firstMatch.matcher === BOLD_PATTERN ? 4 : 2);
        return {
          from: { line: lineIndex, ch: startCh },
          to: { line: lineIndex, ch: endCh }
        };
      }
    }
  }
  return null;
}
var MdToHtmlReportView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return REPORT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Markdown HTML Report";
  }
  getIcon() {
    return "clipboard-list";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("md-to-html-report-view");
    const header = contentEl.createDiv({ cls: "md-to-html-report-header" });
    header.createEl("h3", { text: "Markdown Formatting Report" });
    const refreshButton = header.createEl("button", {
      text: "Refresh",
      cls: "mod-cta"
    });
    refreshButton.addEventListener("click", () => {
      void this.plugin.refreshReport();
    });
    const actions = contentEl.createDiv({ cls: "md-to-html-report-actions" });
    const scanButton = actions.createEl("button", {
      text: "Scan vault"
    });
    scanButton.addEventListener("click", () => {
      void this.plugin.scanVault();
    });
    const convertButton = actions.createEl("button", {
      text: "Convert all",
      cls: "mod-warning"
    });
    convertButton.addEventListener("click", () => {
      void this.plugin.convertVault();
    });
    const items = this.plugin.getProblemFiles();
    if (items.length === 0) {
      contentEl.createDiv({
        text: "No files with markdown formatting issues were found.",
        cls: "md-to-html-report-empty"
      });
      return;
    }
    const list = contentEl.createDiv({ cls: "md-to-html-report-list" });
    for (const item of items) {
      const row = list.createDiv({ cls: "md-to-html-report-row" });
      const info = row.createDiv({ cls: "md-to-html-report-info" });
      info.createDiv({
        text: item.file.basename,
        cls: "md-to-html-report-title"
      });
      info.createDiv({
        text: `${item.count} issue(s) - ${item.file.path}`,
        cls: "md-to-html-report-meta"
      });
      const openButton = row.createEl("button", { text: "Open" });
      openButton.addEventListener("click", () => {
        void this.plugin.openFile(item.file);
      });
      const convertOneButton = row.createEl("button", {
        text: "Convert",
        cls: "mod-warning"
      });
      convertOneButton.addEventListener("click", () => {
        void this.plugin.convertFile(item.file);
      });
    }
  }
};
var MdToHtmlItalicsCheckerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.issueCounts = /* @__PURE__ */ new Map();
  }
  async onload() {
    this.registerView(
      REPORT_VIEW_TYPE,
      (leaf) => new MdToHtmlReportView(leaf, this)
    );
    this.addRibbonIcon("clipboard-list", "Open markdown formatting report", () => {
      void this.activateReportView();
    });
    this.addCommand({
      id: "open-markdown-formatting-report",
      name: "Open markdown formatting report",
      callback: () => {
        void this.activateReportView();
      }
    });
    this.addCommand({
      id: "scan-current-note-markdown-formatting",
      name: "Scan current note for markdown italics and bold",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!this.isMarkdownFile(file)) {
          return false;
        }
        if (!checking) {
          void this.scanFile(file);
        }
        return true;
      }
    });
    this.addCommand({
      id: "convert-current-note-markdown-formatting-to-html",
      name: "Convert markdown italics and bold in current note to HTML",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!this.isMarkdownFile(file)) {
          return false;
        }
        if (!checking) {
          void this.convertFile(file);
        }
        return true;
      }
    });
    this.addCommand({
      id: "scan-vault-markdown-formatting",
      name: "Scan all notes in vault for markdown italics and bold",
      callback: () => {
        void this.scanVault();
      }
    });
    this.addCommand({
      id: "convert-vault-markdown-formatting-to-html",
      name: "Convert markdown italics and bold to HTML in all notes",
      callback: () => {
        void this.convertVault();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        this.addFileMenuItems(menu, file);
      })
    );
    this.registerEvent(
      this.app.workspace.on("files-menu", (menu, files) => {
        this.addFilesMenuItems(menu, files);
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.isMarkdownFile(file)) {
          void this.refreshFileIssueState(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (this.isMarkdownFile(file)) {
          void this.refreshFileIssueState(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.issueCounts.delete(oldPath);
        if (this.isMarkdownFile(file)) {
          void this.refreshFileIssueState(file);
          return;
        }
        this.refreshUi();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        this.issueCounts.delete(file.path);
        this.refreshUi();
      })
    );
    this.app.workspace.onLayoutReady(() => {
      void this.initializeExplorerIndicators();
    });
  }
  async onunload() {
    await this.detachLeavesOfType(REPORT_VIEW_TYPE);
  }
  getProblemFiles() {
    return this.app.vault.getMarkdownFiles().map((file) => ({ file, count: this.issueCounts.get(file.path) ?? 0 })).filter((item) => item.count > 0).sort((a, b) => b.count - a.count || a.file.path.localeCompare(b.file.path));
  }
  async openFile(file) {
    await this.openFileAtFirstIssue(file);
  }
  async refreshReport() {
    await this.rebuildIssueCache();
    this.refreshUi();
  }
  async scanVault() {
    const files = this.app.vault.getMarkdownFiles();
    await this.scanFiles(files);
  }
  async convertVault() {
    const files = this.app.vault.getMarkdownFiles();
    await this.convertFiles(files);
  }
  async convertFile(file) {
    const content = await this.app.vault.read(file);
    const result = convertMarkdownFormatting(content);
    if (result.count === 0) {
      this.issueCounts.set(file.path, 0);
      this.refreshUi();
      new import_obsidian.Notice("Nothing to convert in the current note.");
      return;
    }
    await this.app.vault.modify(file, result.value);
    this.issueCounts.set(file.path, 0);
    this.refreshUi();
    new import_obsidian.Notice(`Converted ${result.count} markdown formatting fragment(s) to HTML tags.`);
  }
  async openFileAtFirstIssue(file) {
    const content = await this.app.vault.read(file);
    const matchLocation = findFirstMatchLocation(content);
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.openFile(file);
    await this.app.workspace.revealLeaf(leaf);
    if (!matchLocation) {
      return;
    }
    const view = leaf.view;
    if (!(view instanceof import_obsidian.MarkdownView)) {
      return;
    }
    const { editor } = view;
    editor.setSelection(matchLocation.from, matchLocation.to);
    editor.setCursor(matchLocation.from);
    editor.scrollIntoView(
      {
        from: matchLocation.from,
        to: matchLocation.to
      },
      true
    );
  }
  isMarkdownFile(file) {
    return file instanceof import_obsidian.TFile && file.extension === "md";
  }
  async initializeExplorerIndicators() {
    await this.refreshVisibleExplorerFiles();
    this.refreshExplorerBadges();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        void this.refreshVisibleExplorerFiles();
      })
    );
  }
  addFileMenuItems(menu, file) {
    if (!this.isMarkdownFile(file)) {
      return;
    }
    menu.addItem((item) => {
      item.setTitle("Scan markdown formatting for HTML conversion").setIcon("search").setSection("md-to-html").onClick(() => {
        void this.scanFile(file);
      });
    });
    menu.addItem((item) => {
      item.setTitle("Convert markdown formatting to HTML").setIcon("wand-sparkles").setSection("md-to-html").onClick(() => {
        void this.convertFile(file);
      });
    });
  }
  addFilesMenuItems(menu, files) {
    const markdownFiles = files.filter((file) => this.isMarkdownFile(file));
    if (markdownFiles.length === 0) {
      return;
    }
    menu.addItem((item) => {
      item.setTitle("Scan markdown formatting in selected notes").setIcon("search").setSection("md-to-html").onClick(() => {
        void this.scanFiles(markdownFiles);
      });
    });
    menu.addItem((item) => {
      item.setTitle("Convert markdown formatting to HTML in selected notes").setIcon("wand-sparkles").setSection("md-to-html").onClick(() => {
        void this.convertFiles(markdownFiles);
      });
    });
  }
  async analyzeFile(file) {
    const content = await this.app.vault.read(file);
    return convertMarkdownFormatting(content);
  }
  async scanFile(file) {
    const result = await this.analyzeFile(file);
    this.issueCounts.set(file.path, result.count);
    this.refreshUi();
    if (result.count === 0) {
      new import_obsidian.Notice("No markdown italics or bold fragments found in the current note.");
      return;
    }
    new import_obsidian.Notice(`Found ${result.count} markdown formatting fragment(s) in the current note.`);
  }
  async scanFiles(files) {
    let affectedFiles = 0;
    let totalMatches = 0;
    for (const file of files) {
      const result = await this.analyzeFile(file);
      this.issueCounts.set(file.path, result.count);
      if (result.count > 0) {
        affectedFiles += 1;
        totalMatches += result.count;
      }
    }
    this.refreshUi();
    if (totalMatches === 0) {
      new import_obsidian.Notice("No markdown italics or bold fragments found in selected notes.");
      return;
    }
    new import_obsidian.Notice(`Found ${totalMatches} issue(s) in ${affectedFiles} selected note(s).`, 8e3);
  }
  async convertFiles(files) {
    let changedFiles = 0;
    let totalMatches = 0;
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const result = convertMarkdownFormatting(content);
      if (result.count === 0) {
        this.issueCounts.set(file.path, 0);
        continue;
      }
      await this.app.vault.modify(file, result.value);
      this.issueCounts.set(file.path, 0);
      changedFiles += 1;
      totalMatches += result.count;
    }
    this.refreshUi();
    if (totalMatches === 0) {
      new import_obsidian.Notice("Nothing to convert in selected notes.");
      return;
    }
    new import_obsidian.Notice(`Converted ${totalMatches} fragment(s) in ${changedFiles} selected note(s).`, 8e3);
  }
  async rebuildIssueCache() {
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const result = await this.analyzeFile(file);
      this.issueCounts.set(file.path, result.count);
    }
  }
  async refreshVisibleExplorerFiles() {
    const elements = document.querySelectorAll(".nav-file-title[data-path]");
    const paths = /* @__PURE__ */ new Set();
    for (const element of elements) {
      const path = element.dataset.path;
      if (path) {
        paths.add(path);
      }
    }
    for (const path of paths) {
      if (this.issueCounts.has(path)) {
        continue;
      }
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!this.isMarkdownFile(file)) {
        continue;
      }
      const result = await this.analyzeFile(file);
      this.issueCounts.set(file.path, result.count);
    }
    this.refreshExplorerBadges();
  }
  async refreshFileIssueState(file) {
    const result = await this.analyzeFile(file);
    this.issueCounts.set(file.path, result.count);
    this.refreshUi();
  }
  refreshUi() {
    this.refreshExplorerBadges();
    this.refreshOpenReportViews();
  }
  refreshExplorerBadges() {
    const elements = document.querySelectorAll(".nav-file-title[data-path]");
    for (const element of elements) {
      const path = element.dataset.path;
      if (!path) {
        continue;
      }
      const count = this.issueCounts.get(path) ?? 0;
      const existingBadge = element.querySelector(`.${BADGE_CLASS}`);
      if (count <= 0) {
        existingBadge?.remove();
        continue;
      }
      if (existingBadge) {
        existingBadge.setAttribute("aria-label", `${count} markdown formatting issues`);
        existingBadge.title = `${count} markdown formatting issue(s)`;
        existingBadge.lastChild?.remove();
        existingBadge.append(String(count));
        continue;
      }
      const badge = document.createElement("span");
      badge.className = BADGE_CLASS;
      badge.setAttribute("aria-label", `${count} markdown formatting issues`);
      badge.title = `${count} markdown formatting issue(s)`;
      badge.setAttribute("role", "button");
      badge.tabIndex = 0;
      badge.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        const file = this.app.vault.getAbstractFileByPath(path);
        if (this.isMarkdownFile(file)) {
          void this.openFileAtFirstIssue(file);
        }
      });
      badge.addEventListener("keydown", (event) => {
        if (event.key !== "Enter" && event.key !== " ") {
          return;
        }
        event.preventDefault();
        event.stopPropagation();
        const file = this.app.vault.getAbstractFileByPath(path);
        if (this.isMarkdownFile(file)) {
          void this.openFileAtFirstIssue(file);
        }
      });
      const iconWrapper = document.createElement("span");
      iconWrapper.className = `${BADGE_CLASS}-icon`;
      (0, import_obsidian.setIcon)(iconWrapper, "alert-circle");
      badge.appendChild(iconWrapper);
      badge.append(String(count));
      element.appendChild(badge);
    }
  }
  refreshOpenReportViews() {
    const leaves = this.app.workspace.getLeavesOfType(REPORT_VIEW_TYPE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof MdToHtmlReportView) {
        view.render();
      }
    }
  }
  async activateReportView() {
    const existingLeaf = this.app.workspace.getLeavesOfType(REPORT_VIEW_TYPE)[0];
    const leaf = existingLeaf ?? this.app.workspace.getRightLeaf(false);
    if (!leaf) {
      return;
    }
    await leaf.setViewState({
      type: REPORT_VIEW_TYPE,
      active: true
    });
    this.refreshOpenReportViews();
    await this.app.workspace.revealLeaf(leaf);
  }
  async detachLeavesOfType(viewType) {
    const leaves = this.app.workspace.getLeavesOfType(viewType);
    for (const leaf of leaves) {
      await leaf.setViewState({ type: "empty" });
    }
  }
};
